from PyQt5 import QtCore, QtGui, QtWidgets
import cryptocode

class Ui_enc(object):
    def encode(self):
        text = self.enctext.toPlainText()
        password = self.encpass.toPlainText()
        encoded = cryptocode.encrypt(text, password)
        self.encoutput.setText(encoded)

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(450, 550)
        MainWindow.setMaximumSize(QtCore.QSize(450, 550))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.enctext = QtWidgets.QTextEdit(self.centralwidget)
        self.enctext.setGeometry(QtCore.QRect(40, 110, 371, 41))
        self.enctext.setObjectName("enctext")
        self.a4 = QtWidgets.QLabel(self.centralwidget)
        self.a4.setGeometry(QtCore.QRect(100, 60, 261, 71))
        self.a4.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.a4.setStyleSheet("font: 8pt \"Acme\";")
        self.a4.setObjectName("a4")
        self.a6 = QtWidgets.QLabel(self.centralwidget)
        self.a6.setGeometry(QtCore.QRect(100, 400, 261, 71))
        self.a6.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.a6.setStyleSheet("font: 8pt \"Acme\";")
        self.a6.setObjectName("a6")
        self.encpass = QtWidgets.QTextEdit(self.centralwidget)
        self.encpass.setGeometry(QtCore.QRect(40, 220, 371, 41))
        self.encpass.setObjectName("encpass")
        self.encoutput = QtWidgets.QTextEdit(self.centralwidget)
        self.encoutput.setGeometry(QtCore.QRect(40, 450, 371, 41))
        self.encoutput.setObjectName("encoutput")
        self.enc = QtWidgets.QLabel(self.centralwidget)
        self.enc.setGeometry(QtCore.QRect(100, 10, 261, 71))
        self.enc.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.enc.setStyleSheet("font: 8pt \"Acme\";")
        self.enc.setObjectName("enc")
        self.a5 = QtWidgets.QLabel(self.centralwidget)
        self.a5.setGeometry(QtCore.QRect(100, 160, 261, 71))
        self.a5.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.a5.setStyleSheet("font: 8pt \"Acme\";")
        self.a5.setObjectName("a5")
        self.enccon = QtWidgets.QPushButton(self.centralwidget)
        self.enccon.setGeometry(QtCore.QRect(160, 320, 151, 41))
        font = QtGui.QFont()
        font.setFamily("Acme")
        font.setPointSize(20)
        self.enccon.setFont(font)
        self.enccon.setObjectName("enccon")
        self.a4.raise_()
        self.a6.raise_()
        self.encpass.raise_()
        self.encoutput.raise_()
        self.enc.raise_()
        self.a5.raise_()
        self.enccon.raise_()
        self.enctext.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 450, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.enccon.clicked.connect(self.encode)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Encrypt"))
        self.a4.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:26pt; font-weight:600;\">TEXT</span></p></body></html>"))
        self.a6.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:26pt; font-weight:600;\">OUTPUT</span></p></body></html>"))
        self.enc.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:36pt; font-weight:600;\">ENCRYPT</span></p></body></html>"))
        self.a5.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:26pt; font-weight:600;\">PASSWORD</span></p></body></html>"))
        self.enccon.setText(_translate("MainWindow", "ENCRYPT"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_enc()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
