from PyQt5 import QtCore, QtGui, QtWidgets
import cryptocode



class Ui_MainWindow(object):
    def open_enc(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_enc()
        self.ui.setupUi(self.window)
        self.window.show()

    def open_dec(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_dec()
        self.ui.setupUi(self.window)
        self.window.show()

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(450, 550)
        MainWindow.setMaximumSize(QtCore.QSize(450, 550))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.mainlbl = QtWidgets.QLabel(self.centralwidget)
        self.mainlbl.setGeometry(QtCore.QRect(100, 20, 261, 121))
        self.mainlbl.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.mainlbl.setStyleSheet("font: 8pt \"Acme\";")
        self.mainlbl.setObjectName("mainlbl")
        self.encmain = QtWidgets.QPushButton(self.centralwidget)
        self.encmain.setGeometry(QtCore.QRect(130, 240, 211, 61))
        self.encmain.setStyleSheet("font: 8pt \"Acme\";\n"
"font: 28pt \"Acme\";")
        self.encmain.setObjectName("encmain")
        self.decmain = QtWidgets.QPushButton(self.centralwidget)
        self.decmain.setGeometry(QtCore.QRect(130, 340, 211, 61))
        self.decmain.setStyleSheet("font: 8pt \"Acme\";\n"
"font: 28pt \"Acme\";")
        self.decmain.setObjectName("decmain")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 450, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.encmain.clicked.connect(self.open_enc)
        self.decmain.clicked.connect(self.open_dec)
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Main Menu"))
        self.mainlbl.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:48pt; font-weight:600;\">CRYPTY</span></p></body></html>"))
        self.encmain.setText(_translate("MainWindow", "ENCRYPT"))
        self.decmain.setText(_translate("MainWindow", "DECRYPT"))

class Ui_enc(object):
    def encode(self):
        text = self.enctext.toPlainText()
        password = self.encpass.toPlainText()
        encoded = cryptocode.encrypt(text, password)
        self.encoutput.setText(encoded)

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(450, 550)
        MainWindow.setMaximumSize(QtCore.QSize(450, 550))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.enctext = QtWidgets.QTextEdit(self.centralwidget)
        self.enctext.setGeometry(QtCore.QRect(40, 110, 371, 41))
        self.enctext.setObjectName("enctext")
        self.a4 = QtWidgets.QLabel(self.centralwidget)
        self.a4.setGeometry(QtCore.QRect(100, 60, 261, 71))
        self.a4.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.a4.setStyleSheet("font: 8pt \"Acme\";")
        self.a4.setObjectName("a4")
        self.a6 = QtWidgets.QLabel(self.centralwidget)
        self.a6.setGeometry(QtCore.QRect(100, 400, 261, 71))
        self.a6.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.a6.setStyleSheet("font: 8pt \"Acme\";")
        self.a6.setObjectName("a6")
        self.encpass = QtWidgets.QTextEdit(self.centralwidget)
        self.encpass.setGeometry(QtCore.QRect(40, 220, 371, 41))
        self.encpass.setObjectName("encpass")
        self.encoutput = QtWidgets.QTextEdit(self.centralwidget)
        self.encoutput.setGeometry(QtCore.QRect(40, 450, 371, 41))
        self.encoutput.setObjectName("encoutput")
        self.enc = QtWidgets.QLabel(self.centralwidget)
        self.enc.setGeometry(QtCore.QRect(100, 10, 261, 71))
        self.enc.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.enc.setStyleSheet("font: 8pt \"Acme\";")
        self.enc.setObjectName("enc")
        self.a5 = QtWidgets.QLabel(self.centralwidget)
        self.a5.setGeometry(QtCore.QRect(100, 160, 261, 71))
        self.a5.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.a5.setStyleSheet("font: 8pt \"Acme\";")
        self.a5.setObjectName("a5")
        self.enccon = QtWidgets.QPushButton(self.centralwidget)
        self.enccon.setGeometry(QtCore.QRect(160, 320, 151, 41))
        font = QtGui.QFont()
        font.setFamily("Acme")
        font.setPointSize(20)
        self.enccon.setFont(font)
        self.enccon.setObjectName("enccon")
        self.a4.raise_()
        self.a6.raise_()
        self.encpass.raise_()
        self.encoutput.raise_()
        self.enc.raise_()
        self.a5.raise_()
        self.enccon.raise_()
        self.enctext.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 450, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.enccon.clicked.connect(self.encode)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Encrypt"))
        self.a4.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:26pt; font-weight:600;\">TEXT</span></p></body></html>"))
        self.a6.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:26pt; font-weight:600;\">OUTPUT</span></p></body></html>"))
        self.enc.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:36pt; font-weight:600;\">ENCRYPT</span></p></body></html>"))
        self.a5.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:26pt; font-weight:600;\">PASSWORD</span></p></body></html>"))
        self.enccon.setText(_translate("MainWindow", "ENCRYPT"))

class Ui_dec(object):
    def decode(self):
        text = self.dectext.toPlainText()
        password = self.decpass.toPlainText()
        decoded = cryptocode.decrypt(text, password)
        if decoded == False:
            self.decoutput.setText("wrong password or text")
        else:
            self.decoutput.setText(decoded)

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(450, 550)
        MainWindow.setMaximumSize(QtCore.QSize(450, 550))
        MainWindow.setDocumentMode(False)
        MainWindow.setDockNestingEnabled(True)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.a3 = QtWidgets.QLabel(self.centralwidget)
        self.a3.setGeometry(QtCore.QRect(100, 400, 261, 71))
        self.a3.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.a3.setStyleSheet("font: 8pt \"Acme\";")
        self.a3.setObjectName("a3")
        self.dec = QtWidgets.QLabel(self.centralwidget)
        self.dec.setGeometry(QtCore.QRect(100, 10, 261, 71))
        self.dec.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.dec.setStyleSheet("font: 8pt \"Acme\";")
        self.dec.setObjectName("dec")
        self.decpass = QtWidgets.QTextEdit(self.centralwidget)
        self.decpass.setGeometry(QtCore.QRect(40, 220, 371, 41))
        self.decpass.setObjectName("decpass")
        self.a2 = QtWidgets.QLabel(self.centralwidget)
        self.a2.setGeometry(QtCore.QRect(100, 160, 261, 71))
        self.a2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.a2.setStyleSheet("font: 8pt \"Acme\";")
        self.a2.setObjectName("a2")
        self.dectext = QtWidgets.QTextEdit(self.centralwidget)
        self.dectext.setGeometry(QtCore.QRect(40, 110, 371, 41))
        self.dectext.setObjectName("dectext")
        self.a1 = QtWidgets.QLabel(self.centralwidget)
        self.a1.setGeometry(QtCore.QRect(90, 60, 281, 71))
        self.a1.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.a1.setStyleSheet("font: 8pt \"Acme\";")
        self.a1.setObjectName("a1")
        self.decoutput = QtWidgets.QTextEdit(self.centralwidget)
        self.decoutput.setGeometry(QtCore.QRect(40, 450, 371, 41))
        self.decoutput.setObjectName("decoutput")
        self.deccon = QtWidgets.QPushButton(self.centralwidget)
        self.deccon.setGeometry(QtCore.QRect(150, 310, 151, 41))
        font = QtGui.QFont()
        font.setFamily("Acme")
        font.setPointSize(20)
        self.deccon.setFont(font)
        self.deccon.setObjectName("deccon")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 450, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.deccon.clicked.connect(self.decode)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Decrypt"))
        self.a3.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:26pt; font-weight:600;\">OUTPUT</span></p></body></html>"))
        self.dec.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:36pt; font-weight:600;\">DECRYPT</span></p></body></html>"))
        self.a2.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:26pt; font-weight:600;\">PASSWORD</span></p></body></html>"))
        self.a1.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:26pt; font-weight:600;\">ENCRYPTED TEXT</span></p></body></html>"))
        self.deccon.setText(_translate("MainWindow", "DECRYPT"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())